// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvNBhSYGiHrFCyCuLK5Y8o9myQYJmMeY0',
    appId: '1:289160222253:web:91eeb3af649fcd486b4aa4',
    messagingSenderId: '289160222253',
    projectId: 'quicknotes-flutter-myproject',
    authDomain: 'quicknotes-flutter-myproject.firebaseapp.com',
    storageBucket: 'quicknotes-flutter-myproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoPuv_Dc7l_xIoPNf2geE1bmcbzJi1wm4',
    appId: '1:289160222253:android:c8865901490242376b4aa4',
    messagingSenderId: '289160222253',
    projectId: 'quicknotes-flutter-myproject',
    storageBucket: 'quicknotes-flutter-myproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCduQXihKRdPAPhQ0hmuFfVm0ime27Bps',
    appId: '1:289160222253:ios:3a40f8f60cea0ccf6b4aa4',
    messagingSenderId: '289160222253',
    projectId: 'quicknotes-flutter-myproject',
    storageBucket: 'quicknotes-flutter-myproject.firebasestorage.app',
    iosBundleId: 'com.example.quicknotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvNBhSYGiHrFCyCuLK5Y8o9myQYJmMeY0',
    appId: '1:289160222253:web:1955ab8245c117136b4aa4',
    messagingSenderId: '289160222253',
    projectId: 'quicknotes-flutter-myproject',
    authDomain: 'quicknotes-flutter-myproject.firebaseapp.com',
    storageBucket: 'quicknotes-flutter-myproject.firebasestorage.app',
  );
}
